### ISSUE TITLE
Openssl is not detetected on installation

### ISSUE THREAD

**Issue by Bendrien** [amethyst/tools#61]
Hello, i wont to paly around with amethyst and tried to install the recomanded tooling amethyst_tools.
unfortunately during installation i stumbled over the 'Unable to detect OpenSSL version' error.
Im using arch linux and have openssl 1.1.1 and 1.0 installed. Here is the stack backtrace:

```
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::begin_panic
   6: build_script_build::main
   7: std::rt::lang_start::{{closure}}
   8: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
   9: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  10: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  11: main
  12: __libc_start_main
  13: _start
```

Im kinda noob in such things and dont know how to proceed from here on and would appreciate any support.

**Comment by torkleyy** [comment]
Hey, there's an open PR to fix this already ;)

**Comment by LiaRowan** [comment]
What's the status of this PR? I'm also hoping to get started with Amethyst (on Arch Linux as well), but can't install the tools.

The PR looks like it's approved by @Moxinilian, but hasn't been merged yet. Anything I can do to help?

**Comment by Moxinilian** [comment]
Sorry about that. #60 is getting merged now.

**Comment by KYSXD** [comment]
Hi!
I'm getting the same error running `$ cargo install amethyst_tools` on an empty project:

```rust
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/tmp/cargo-installupFQC6/release/build/openssl-d95cc14a80be27c4/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/kysxd/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::begin_panic
   6: build_script_build::main
   7: std::rt::lang_start::{{closure}}
   8: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
   9: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  10: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  11: main
  12: __libc_start_main
  13: _start
```

I'm running on Manjaro 17.1.12 (Arch based) with `openssl 1.1.1-1` and `openssl-1.0 1.0.2.p-1` installed.

Am I doing something wrong? I thought that with #60 I should have no problem.

Any help is appreciated.

**Comment by torkleyy** [comment]
Should be fixed in the new version.
