### ISSUE TITLE
OpenSSL panic.

### ISSUE THREAD

**Issue by jamiltron** [amethyst/tools#63]
Hello, I am trying to install amethyst_tools 0.7.2 using cargo 1.29.0 and rustc version 1.29.2 on Arch Linux 4.18.14 with OpenSSL 1.1.1-1 installed from Arch's package manager.

When running `env RUST_BACKTRACE=1 cargo install amethyst_tools` I get the following error:

```
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/tmp/cargo-installnyHFph/release/build/openssl-a1b7b949fe7f2e6f/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::begin_panic
   6: build_script_build::main
   7: std::rt::lang_start::{{closure}}
   8: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
   9: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  10: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  11: main
  12: __libc_start_main
  13: _start

warning: build failed, waiting for other jobs to finish...
error: failed to compile `amethyst_tools v0.7.2`, intermediate artifacts can be found at `/tmp/cargo-installnyHFph`
```

I assume this is related to an OpenSSL version mismatch?

**Comment by torkleyy** [comment]
Hey, this should be fixed already. Probably we forgot to publish a new version.

**Comment by torkleyy** [comment]
Should be fixed after an update (`cargo install --force amethyst_tools`).

**Comment by jamiltron** [comment]
Thanks! I'll check later today.

**Comment by torkleyy** [comment]
@jamiltron Any update? :)

**Comment by torkleyy** [comment]
I'm wondering if we should just link statically to avoid this issue in the future.

**Comment by torkleyy** [comment]
Closing since this should be fixed now.
