### ISSUE TITLE
Question: is x11 server supported?

### ISSUE THREAD

**Issue by KYSXD** [amethyst/tools#67]
Trying to run a working app with WSL (ubuntu) prints the following error:

(also happens on newly created projects via CLI)

Is x11 not supported? or am I missing something?

```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at libcore/result.rs:808
  10: gfx_window_glutin::init_raw
             at /home/kysxd/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.26.0/src/lib.rs:144
  11: gfx_window_glutin::init
             at /home/kysxd/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.26.0/src/lib.rs:67
  12: amethyst_renderer::renderer::init_backend
             at /home/kysxd/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_renderer-0.9.0/src/renderer.rs:305
  13: amethyst_renderer::renderer::RendererBuilder::build
             at /home/kysxd/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_renderer-0.9.0/src/renderer.rs:213
  14: <amethyst_renderer::system::RenderSystem<P>>::build
             at /home/kysxd/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_renderer-0.9.0/src/system.rs:58
  15: <amethyst_renderer::bundle::RenderBundle<'c, B, P> as amethyst_core::bundle::SystemBundle<'a, 'b>>::build
             at /home/kysxd/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_renderer-0.9.0/src/bundle.rs:115
  16: amethyst::game_data::GameDataBuilder::with_bundle
             at /home/kysxd/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.9.0/src/game_data.rs:214
  17: titan::main
             at src/main.rs:29
  18: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  19: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  20: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  21: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  22: std::rt::lang_start
             at libstd/rt.rs:74
  23: main
  24: __libc_start_main
  25: _start
```

**Comment by Xaeroxe** [comment]
X11 is supported, however usually when we get this error it means the graphics backend didn't report any working pixel formats.  You might need to check your drivers.

**Comment by torkleyy** [comment]
I don't think WSL supports any graphics.
